---
name: main

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ${{ vars.ACTIONS_RUNNER }}
    strategy:
      fail-fast: false
      matrix:
        go: ["1.17.x", "1.18.x"]
    steps:
      - name: Checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2

      - name: License check
        run: ./scripts/licensecheck.sh

      - name: Go installation
        uses: actions/setup-go@bfdd3570ce990073878bf10f6b2d79082de49492 # v2
        with:
          go-version: ${{ matrix.go }}

      - name: Go dependencies installation
        run: go get -d ./...

      - name: Golint installation
        run: go get -u golang.org/x/lint/golint

      - name: Build
        run: go build ./...

      - name: Lint
        run: ./scripts/golint.sh

      - name: Vet
        run: go vet ./...

      - name: Test
        run: go test -v ./...
